### ISSUE TITLE
Audio Message not opening

### ISSUE THREAD

**Issue by niteshorntech** [cometchat-pro/ios-chat-ui-kit#2]
Hello Team,

Audio Messages are going through but it is not opening on the Recipient's phone, also on sender phone, this is working when we go back and come again

**Comment by pushpsenairekar2911** [comment]
hello @niteshorntech, 

We have added support for audio notes in our latest UI Kit release i.e 2.0.2. Please, clone the fresh project. 

Closing this issue because no longer needed.
