### ISSUE TITLE
Group Creation not updating Realtime

### ISSUE THREAD

**Issue by niteshorntech** [cometchat-pro/ios-chat-ui-kit#3]
Once the Group is formed, it does not immediately come up in the Groups list. You have to click Groups to see the recently created Group: this is not updating realtime, because when we click on the group again this is showing the new group

**Comment by pushpsenairekar2911** [comment]
Hello @niteshorntech, 

We are tracking your request on https://feedback.cometchat.com/cometchat-pro-feature-requests/p/send-a-real-time-event-when-someone-creates-a-group-via-dashboard-or-api

You'll get notified once we release this feature. 

Closing this issue because no longer needed.
