### ISSUE TITLE
Real Time user now showing while adding in Social Engine

### ISSUE THREAD

**Issue by niteshorntech** [cometchat-pro/ios-chat-ui-kit#5]
While adding the user as a friend, the user is not showing in the comet chat users instantly: Real-Time users are not updating
When we are logging out and login in the application again this is showing.

**Comment by pushpsenairekar2911** [comment]
Hello @niteshorntech , 

We are tracking your request on: https://feedback.cometchat.com/cometchat-pro-feature-requests/p/real-time-event-when-someone-addsremoves-a-friend-via-dashboard-or-api

You'll get notified once we release this feature. 

Closing this issue because no longer needed.
