### ISSUE TITLE
[2.0.8] Can't find protocol declaration for all CometChatDelegate in -Swift.h file.

### ISSUE THREAD

**Issue by TheikChan** [cometchat-pro/ios-chat-ui-kit#6]
<img width="1292" alt="Screenshot 2020-05-18 at 11 48 32 AM" src="https://user-images.githubusercontent.com/13691817/82184097-138f3b80-990d-11ea-9d92-c418dca04388.png">

**Comment by TheikChan** [comment]
<img width="1292" alt="Screenshot 2020-05-18 at 11 48 32 AM" src="https://user-images.githubusercontent.com/13691817/82176739-9d370d00-98fd-11ea-89bd-486ffc547a12.png">

**Comment by pushpsenairekar2911** [comment]
Hello @TheikChan, It seems that you're running the objective C project in the simulator. Please read our readme.md instructions for running objective C project. Also, run the project on physical device. 

Closing this issue because no longer needed.
